=== Sandish12/GIFTCARD/Catalog_20049021.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Store" type="StoreType">
    <xs:annotation>
      <xs:documentation>
    Author: Sandish Dangol
    London Met: 20049021
    Date: 03/25/2022
</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:complexType name="logoType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="id" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="homeType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="id" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="supportType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="id" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="mycardType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="id" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="refillType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="id" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="companyType">
    <xs:sequence>
      <xs:element type="xs:string" name="title" />
      <xs:element type="xs:string" name="moto" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="navbarType">
    <xs:sequence>
      <xs:element type="logoType" name="logo" />
      <xs:element type="homeType" name="home" />
      <xs:element type="supportType" name="support" />
      <xs:element type="mycardType" name="mycard" />
      <xs:element type="refillType" name="refill" />
      <xs:element type="companyType" name="company" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="imgType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="id" use="optional" />
        <xs:attribute type="xs:string" name="src" use="optional" />
        <xs:attribute type="xs:string" name="alt" use="optional" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="detailType">
    <xs:sequence>
      <xs:element type="xs:string" name="country" />
      <xs:element type="xs:string" name="cost" />
      <!-- <xs:element type="xs:string" name="availability" /> -->
      <xs:element name="availability">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Available" />
            <xs:enumeration value="UnAvailable" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:string" name="discount">
        <xs:annotation>
          <xs:documentation> discount us optional discount us optional</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="xs:float" name="avilablecards" />
      <xs:element type="xs:string" name="customers" />
      <xs:element type="xs:string" name="description" />
      <xs:element type="xs:float" name="rating">
        <xs:annotation>
          <xs:documentation> review is also optional review is also optional</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="btnType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="id" use="optional" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="giftcardType">
    <xs:sequence>
      <xs:element type="xs:string" name="name" />
      <xs:element type="imgType" name="img" />
      <xs:element type="detailType" name="detail" minOccurs="0" />
      <xs:element type="xs:string" name="country" minOccurs="0" />
      <xs:element type="xs:string" name="cost" minOccurs="0" />
      <xs:element type="xs:string" name="availability" minOccurs="0" />
      <xs:element type="xs:string" name="discount" minOccurs="0">
        <xs:annotation>
          <xs:documentation> discount us optional discount us optional discount us optional discount us optional</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="xs:float" name="avilablecards" minOccurs="0" />
      <xs:element type="xs:string" name="customers" minOccurs="0" />
      <xs:element type="xs:string" name="description" minOccurs="0" />
      <xs:element type="xs:float" name="rating" minOccurs="0">
        <xs:annotation>
          <xs:documentation> review is also optional review is also optional review is also optional review is also optional</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="btnType" name="btn" />
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="optional" />
    <xs:attribute type="xs:string" name="type" use="optional" />
  </xs:complexType>
  <xs:complexType name="topsellerType">
    <xs:sequence>
      <xs:element type="giftcardType" name="giftcard" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="cardType">
    <xs:sequence>
      <xs:element type="topsellerType" name="topseller" maxOccurs="unbounded" minOccurs="0" />
      <xs:element type="giftcardType" name="giftcard" maxOccurs="unbounded" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="footerType">
    <xs:sequence>
      <xs:element type="xs:string" name="store" />
      <xs:element type="xs:string" name="address" />
      <xs:element type="xs:float" name="phone" />
      <xs:element type="xs:string" name="facebook" />
      <xs:element type="xs:string" name="instagram" />
      <xs:element type="xs:string" name="website" />
      <xs:element type="xs:string" name="email" />
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" />
  </xs:complexType>
  <xs:complexType name="StoreType">
    <xs:sequence>
      <xs:element type="navbarType" name="navbar">
        <xs:annotation>
          <xs:documentation> navigation bar </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="cardType" name="card" />
      <xs:element type="footerType" name="footer">
        <xs:annotation>
          <xs:documentation>footer </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Sandish12/GIFTCARD/Catalog_20049021.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="Catalog_20049021.css" type="text/css"?>
<!--
    Author: Sandish Dangol
    London Met: 20049021
    Date: 03/25/2022
-->
<Store xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalog_20049021.xsd">
  
  <!-- navigation bar -->
  <navbar>
    <logo id="logo_img"></logo>
    <home id="nav">Home</home>
    <support id="nav">Support</support>
    <mycard id="nav">Cart</mycard>
    <refill id="nav">Refill</refill>
    <company>
      <title>Newa's Gift Store</title>
      <moto>A card thats gifts.</moto>
    </company>
  </navbar>

  <card>
    <topseller>
      <giftcard id="MLBB" type="Digital">
        <name> MLBB Gift Card </name>
        <img id="MLBB_img" src="ml.jpg" alt="" />
        <detail>
          <country> UK </country>
          <cost> 40$ </cost>
          <availability>Available</availability>
          <!-- discount us optional-->
          <discount>25% off (For regular customers)</discount>
          <avilablecards> 60 </avilablecards>
          <customers> 2k </customers>
          <description>
            <![CDATA[Creating an easy way of purchasing any skins for the gift card users at anytime and anyplace.]]>
          </description>
          <!-- review is also optional-->
          <rating> 7 </rating>
        </detail>
        <btn id="button"> BuyNow</btn>
      </giftcard>
    </topseller>

    <topseller>
      <giftcard id="KFC" type="Physical">
        <name> KFC Gift Card </name>
        <img id="KFC_img" src="kfc.jpg" alt="" />
        <detail>
          <country> UK </country>
          <cost> 65$ </cost>
          <availability>UnAvailable</availability>
          <!-- discount us optional-->
          <discount> 8% off </discount>
          <avilablecards> 0 </avilablecards>
          <customers> 200k </customers>
          <description>
            <![CDATA[The new way of paying the bills to enjoy meal with friends and family without carrying any money.]]>
          </description>
          <!-- review is also optional-->
          <rating> 9.2 </rating>
        </detail>
        <btn id="button"> BuyNow</btn>
      </giftcard>
    </topseller>


    <giftcard id="PAY" type="Digital">
      <name> Paypal Gift Card </name>
      <img id="Paypal_img" src="paypal.jpg" alt="" />
      <country> UK </country>
      <cost> 45$</cost>
      <availability>Available</availability>
      <!-- discount us optional-->
      <discount>8% off </discount>
      <avilablecards> 35 </avilablecards>
      <customers> 2M </customers>
      <description>
        <![CDATA[To give and get gifts for different kinds of parties or celebrations incase of not having any physical gift.]]>
      </description>
      <!-- review is also optional-->
      <rating> 8 </rating>
      <btn id="button"> BuyNow</btn>
    </giftcard>

    <giftcard id="DIC" type="Digital">
      <name> Discord Gift Card </name>

      <img id="discord_img" src="discord.jpg" alt="" />

      <country> UK </country>
      <cost> 10$</cost>
      <availability>Available</availability>
      <!-- discount us optional-->
      <discount>8% off </discount>
      <avilablecards>  22 </avilablecards>
      <customers> 3.1k </customers>
      <description>
        <![CDATA[Creating an easy way of boosting the server for the creators and gamers to communicate with their friends.]]>
      </description>
      <!-- review is also optional-->
      <rating> 8.5 </rating>
      <btn id="button"> BuyNow</btn>
    </giftcard>

    <giftcard id="DP" type="physical">
      <name> Domino's pizza Gift Card </name>

      <img id="dominos_img" src="pizza.jpg" alt="" />

      <country> UK </country>
      <cost> 50$</cost>
      <availability>Available</availability>
      <!-- discount us optional-->
      <discount>8% off </discount>
      <avilablecards> 90 </avilablecards>
      <customers> 188.5k </customers>
      <description>
        <![CDATA[Creating an easy way of paying for any kind of pizza's through card insted of physical money.]]>
      </description>
      <!-- review is also optional-->
      <rating> 7.8 </rating>
      <btn id="button"> BuyNow</btn>
    </giftcard>

    <giftcard id="MLBB" type="Digital">
      <name> XBOX 360 Gift Card </name>

      <img id="XBOX_img" src="xbox.jpg" alt="" />

      <country> UK </country>
      <cost> 50$</cost>
      <availability>Available</availability>
      <!-- discount us optional-->
      <discount>8% off </discount>
      <avilablecards> 15 </avilablecards>
      <customers> 3k </customers>
      <description>
        <![CDATA[Creating an easy way of purchasing any games that anyone uses XBOX.]]>
          </description>
      <!-- review is also optional-->
      <rating> 9 </rating>
      <btn id="button"> BuyNow</btn>
    </giftcard>

  </card>
  <!--footer -->
  <footer id="footer">
    <store>Newa's Gift Card </store>
    <address> London </address>
    <phone>  9849277004 </phone>
    <facebook> Facebook (Newa's Gift Card) </facebook>
    <instagram> Instagram (Newa's Gift Card) </instagram>
    <website> newagiftcard.com</website>
    <email> newagiftcard@gmail.com</email>
  </footer>
</Store>
